site_name: Password Thing

nav:
    - Home: index.md
    - Configuration: configuration.md
    - Technical: technical.md
    - Hardware and Software: hardware_and_software.md

theme:
  name: 'material'
